/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int grant_fs(char *, char *);
int revoke_fs(char *, char *);

int grant_fs(char * identity __attribute__((unused)), char * path __attribute__((unused))) {
    return (emilyos_fsacl_grant(identity, path));
}

int revoke_fs(char * identity __attribute__((unused)), char * path __attribute__((unused))) {
    return (emilyos_fsacl_revoke(identity, path));
}

